#!/usr/bin/env bash
BACON_REPO_ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
${BACON_REPO_ROOT}/build/sim_group_dynamic_timer_prbt --g  --r 0
${BACON_REPO_ROOT}/build/sim_group_dynamic_timer_prbt --g  --r 1
${BACON_REPO_ROOT}/build/sim_group_dynamic_timer_prbt --g  --r 2
${BACON_REPO_ROOT}/build/sim_group_dynamic_timer_prbt --g  --r 3
${BACON_REPO_ROOT}/build/sim_group_dynamic_timer_prbt --g  --r 4
${BACON_REPO_ROOT}/build/sim_group_dynamic_timer_prbt --g  --r 5
${BACON_REPO_ROOT}/build/sim_group_dynamic_timer_prbt --g  --r 6
${BACON_REPO_ROOT}/build/sim_group_dynamic_timer_prbt --g  --r 7
${BACON_REPO_ROOT}/build/sim_group_dynamic_timer_prbt --g  --r 8
${BACON_REPO_ROOT}/build/sim_group_dynamic_timer_prbt --g  --r 9
${BACON_REPO_ROOT}/build/sim_group_dynamic_timer_prbt --g  --r 10
${BACON_REPO_ROOT}/build/sim_group_dynamic_timer_prbt --g  --r 11
${BACON_REPO_ROOT}/build/sim_group_dynamic_timer_prbt --g  --r 12
${BACON_REPO_ROOT}/build/sim_group_dynamic_timer_prbt --g  --r 13
${BACON_REPO_ROOT}/build/sim_group_dynamic_timer_prbt --g  --r 14
${BACON_REPO_ROOT}/build/sim_group_dynamic_timer_prbt --g  --r 15
${BACON_REPO_ROOT}/build/sim_group_dynamic_timer_prbt --g  --r 16
${BACON_REPO_ROOT}/build/sim_group_dynamic_timer_prbt --g  --r 17
${BACON_REPO_ROOT}/build/sim_group_dynamic_timer_prbt --g  --r 18
${BACON_REPO_ROOT}/build/sim_group_dynamic_timer_prbt --g  --r 19
${BACON_REPO_ROOT}/build/sim_group_dynamic_timer_prbt --g  --r 20
${BACON_REPO_ROOT}/build/sim_group_dynamic_timer_prbt --g  --r 21
${BACON_REPO_ROOT}/build/sim_group_dynamic_timer_prbt --g  --r 22
${BACON_REPO_ROOT}/build/sim_group_dynamic_timer_prbt --g  --r 23
${BACON_REPO_ROOT}/build/sim_group_dynamic_timer_prbt --g  --r 24
${BACON_REPO_ROOT}/build/sim_group_dynamic_timer_prbt --g  --r 25
${BACON_REPO_ROOT}/build/sim_group_dynamic_timer_prbt --g  --r 26
${BACON_REPO_ROOT}/build/sim_group_dynamic_timer_prbt --g  --r 27
${BACON_REPO_ROOT}/build/sim_group_dynamic_timer_prbt --g  --r 28
${BACON_REPO_ROOT}/build/sim_group_dynamic_timer_prbt --g  --r 29
${BACON_REPO_ROOT}/build/sim_group_dynamic_timer_prbt --g  --r 30
${BACON_REPO_ROOT}/build/sim_group_dynamic_timer_prbt --g  --r 31
${BACON_REPO_ROOT}/build/sim_group_dynamic_timer_prbt --g  --r 32
${BACON_REPO_ROOT}/build/sim_group_dynamic_timer_prbt --g  --r 33
${BACON_REPO_ROOT}/build/sim_group_dynamic_timer_prbt --g  --r 34
${BACON_REPO_ROOT}/build/sim_group_dynamic_timer_prbt --g  --r 35
${BACON_REPO_ROOT}/build/sim_group_dynamic_timer_prbt --g  --r 36
${BACON_REPO_ROOT}/build/sim_group_dynamic_timer_prbt --g  --r 37
${BACON_REPO_ROOT}/build/sim_group_dynamic_timer_prbt --g  --r 38
${BACON_REPO_ROOT}/build/sim_group_dynamic_timer_prbt --g  --r 39
${BACON_REPO_ROOT}/build/sim_group_dynamic_timer_prbt --g  --r 40

